import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layouts/Navbar";
import Footer from "./components/layouts/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links: NavLinks[] = [
  { title: "Products", isActive: true },
  { title: "Team", isActive: false },
  { title: "Contact Us", isActive: false },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section>
          {" "}
          <Navbar items={links} />
        </section>
        <section> {children}</section>
        <section>
          <Footer />
        </section>
      </body>
    </html>
  );
}
